### ISSUE TITLE
dyld: Symbol not found

### ISSUE THREAD

**Issue by 1ncend1ary** [zackelia/bclm#6]
Hello! I am really interested in this project!

However, this error shows up when running the `bclm` command in terminal after installing with `brew` or from release.
I am running MacOS 10.13.6, so I can't build it from source.
```
dyld: Symbol not found: _$s17StringLiteralTypes013ExpressibleByaB0PTl
  Referenced from: /usr/local/bin/bclm
  Expected in: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/libswiftCore.dylib
 in /usr/local/bin/bclm
[1]    6923 abort      bclm
```
Can provide any additional info if necessary.

**Comment by zackelia** [comment]
I'm gonna take a look at this some more, I think I know a solution. Can you tell me what your `swift -version` is?

**Comment by 1ncend1ary** [comment]
```
Apple Swift version 4.2.1 (swiftlang-1000.11.42 clang-1000.11.45.1)
Target: x86_64-apple-darwin17.7.0
```

**Comment by TomXia** [comment]
I've encountered the same issue on 10.13.6 with Xcode 10.1.

My solution is to download the latest swift-toolchain from https://swift.org/download/, and extract the necessary libs to *.xctoolchain/usr/lib/swift/macosx/libswift*. Don't forget to backup the old libs.

It's worth mentioning that all your old swift programs, including the swift complier provided by Xcode won't work anymore. But it is fine for me, because I do not use them.

Again, I'm not that familiar with Apple's toolchain or Swift, so there must be a better way. Guess that it has something to do with static link option when building the code.

And thanks @zackelia for your efforts.

**Comment by wangyiwei2015** [comment]
I'm running 10.13.6
My solution is installing _Swift 5 Runtime Support for Command Line Tools_.
You may search and download it form support.apple.com

**Comment by zackelia** [comment]
Updated README to reflect this solution.
